### ISSUE TITLE
AddDbContext was called with configuration, but the context type 'ContextClass' only declares a parameterless constructor?

### ISSUE THREAD

**Issue by AJMalik007** [urfnet/URF.Core.Sample#13]
# Detail
I am trying to create asp.net core application and use scaffold-dbcontext to generate class. when I run this app it shows me the error. I already follow some answer on stackoverflow with the same issue but mine remains.

# Error

AddDbContext was called with configuration, but the context type 'MyContext' only declares a parameterless constructor. This means that the configuration passed to AddDbContext will never be used. If configuration is passed to AddDbContext, then 'puffinDBContext' should declare a constructor that accepts a DbContextOptions<MyContext> and must pass it to the base constructor for DbContext.

`public partial class MyContext: DbContext
{

    public MyContext(DbContextOptions<MyContext> options) : base(options)
    {
    }

    public virtual DbSet<Answer> Answer { get; set; }
    public virtual DbSet<Attachment> Attachment { get; set; }
    public virtual DbSet<Category> Category { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {

        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=MyContext;Trusted_Connection=True;");
        }
    protected override void OnModelCreating(ModelBuilder modelBuilder) { .... }
}`

# Startup Class

```
public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        services.AddMvc()
       .AddJsonOptions(options =>
           options.SerializerSettings.PreserveReferencesHandling = PreserveReferencesHandling.All);

        services.AddDbContext<MyContext>(options => options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
    }
```

**Comment by lelong37** [comment]
This really wan't an issue with URF.Core, as it was more of an issue of Visual Studio Design Tools having to new up an instance of a DbContext for EF Tools e.g. generating/scaffolding API Controllers w/ EF etc.

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dbcontext-creation
https://github.com/urfnet/URF.Core.Sample/pull/15
https://github.com/urfnet/URF.Core.Sample/blob/master/Northwind.Data/NorthwindContextFactory.cs
