### ISSUE TITLE
Microsoft.AspNetCore.OData

### ISSUE THREAD

**Issue by ugomonte** [urfnet/URF.Core.Sample#2]
Hi, first of all thank you very much for this work. I apprecite very much.

I have downloaded this sample solution and opened with visual studio community (version 15.5.7) but i have got this error:
----------------------------
Errore	NU1102	Il pacchetto Microsoft.AspNetCore.OData con versione (>= 7.0.0-Nightly201802141312) non è stato trovato
  - Trovata/e 9 versione/i in nuget.org [ Versione più vicina: 7.0.0-beta1 ]
  - Trovata/e 0 versione/i in Microsoft Visual Studio Offline Packages	Northwind.Api	C:\Users\ugo\Documents\Visual Studio 2017\Projects\URF.Core.Sample-master\Northwind.Api\Northwind.Api.csproj	1	
--------------------------
Have I to uninstall Microsoft.AspNetCore.OData 7.0.0-Nightly201802141312 and install the available version 7.0.0-beta1 ?

Thanks very much.
best regards.
Ugo Montefiori

**Comment by Domitnator** [comment]
Yes! I ran into the same issue but you can just upgrade the nuget package. 

I guess @lelong37  will update the nuget package in the near future?

**Comment by ugomonte** [comment]
Ok thank you very much.
