### ISSUE TITLE
Upgrading Microsoft.AspNetCore, Microsoft.VisualStudio.Web packages brakes the app.

### ISSUE THREAD

**Issue by IvanFarkas** [urfnet/URF.Core.Sample#22]
Upgrading **Microsoft.AspNetCore**, **Microsoft.VisualStudio.Web** packages brakes the app.

```
-    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-preview1-final" />
-    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.1.0-preview1-final" />
+    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-rc1-final" />
+    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.1.0-rc1-final" />
-    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-preview1-final" />
-    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGenerators.Mvc" Version="2.1.0-preview2-final" />
+    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-rc1-final" />
+    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGenerators.Mvc" Version="2.1.0-rc1-final" />
```

Output

```
HTTP Error 502.5 - Process Failure

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect

For more information visit: https://go.microsoft.com/fwlink/?LinkID=808681

```

**Comment by tonysneed** [comment]
Why upgrade those?

**Comment by tonysneed** [comment]
If you upgrade to AspNet Core 2.1, you need to use the Preview version of Visual Studio. Otherwise leave those packages alone and you can use the current version of Visual Studio.

**Comment by IvanFarkas** [comment]
We are using

- dotnet 2.1.300-preview1-008174
- .NET Core RC1
- VS 2017 v15.8.0 Preview 1.1

**Alpha**, **Beta**, **Preview** is NO GO with most enterprise, but **RC**, **RTM** is.
Could you please update to RC instead of preview, if possible?
If not possible we just wait for **RTM**.

**Thank you very much for the excellent work!**

**Comment by tonysneed** [comment]
URF v 1.0  should be good for you because it uses only the RC bits of EF Core.

The version of the .NET Core SDK you should be using is 2.1.300-rc1-008673, which works with VS 2017 RTM.  Roll back to these versions and you should be fine.

**Comment by lelong37** [comment]
@IvanFarkas are we good on this issue, can we close this out?

**Comment by tonysneed** [comment]
Let’s re-open if needed.
